### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by shidaying** [auxmoney/grafana-waterfall-panel#8]
**on debian system**

install the plugin with below code
```
grafana-cli plugins install auxmoney-waterfall-panel
```
but failed with below message

```
failed to find plugin 'auxmoney-waterfall-panel' in plugin repository. Please check if plugin ID is correct
Error: ✗ plugin not found
```

**Comment by cawolf** [comment]
Hi @shidaying ,

thanks for reporting this error. I can reproduce that behaviour on our systems.

I opened an issue at grafana/grafana-plugin-repository#994 . Depending on the outcome of the issue, we will take actions to make the plugin installable by `grafana-cli`.

In the meantime, you can install the plugin manually from [grafana.com](https://grafana.com/grafana/plugins/auxmoney-waterfall-panel/?tab=installation) and extract it in your plugins folder.

**Comment by cawolf** [comment]
While we fixed the issue on our side, please have some patience until the plugin repository update is done as well.

**Comment by cawolf** [comment]
The PR is open to publish the fixed version on grafana.com:
grafana/grafana-plugin-repository#1000
